# Generated by Django 3.2 on 2021-04-27 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pyyyc", "0001_initial_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="meetup_link",
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(null=True)),
                ("slides_links", models.URLField(null=True)),
                ("code_link", models.URLField(null=True)),
                ("blog_link", models.URLField(null=True)),
                ("video_link", models.URLField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pyyyc.event"
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pyyyc.presenter",
                    ),
                ),
            ],
        ),
    ]
