# Generated by Django 3.2 on 2021-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyyyc", "0002_talk_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="meetup_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
