# Generated by Django 3.2 on 2021-04-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyyyc", "0003_add_event_processed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presenter",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="talk", old_name="slides_links", new_name="slides_link"
        ),
        migrations.AlterField(
            model_name="talk",
            name="blog_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="talk",
            name="code_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="talk",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="talk",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
