# Generated by Django 3.2 on 2021-05-03 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pyyyc", "0004_consistent_link_field_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="talk",
            name="slides_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="talk",
            name="slides_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pyyyc.talkartifact",
            ),
        ),
    ]
